### ISSUE TITLE
zfs Native encryption request

### ISSUE THREAD

**Issue by bossey1** [peternickol/script.zfsbootmenu.ubuntu#2]
Hi
Any chance of adding an zfs native encryption bit in here?

**Comment by peternickol** [comment]
This was written primarily as a tool to do a series of automated installs for a client. I published it so that client could have access if needed later. 

Essentially all i'm doing is automating the instructions found here: https://docs.zfsbootmenu.org/en/v2.3.x/guides/ubuntu/jammy-uefi.html

The only thing different from the instructions was the client's requirement for a separate /var device. 

It should not be a problem to add encryption by using the modified encryption instructions on the zfsbootmenu website.

There are some changes during the zpool creation process and a couple other places that manage the encryption key, build the initramfs, and generate the zfsbootmenu. I've highlighted those places in the instructions below. 

https://docs.zfsbootmenu.org/en/v2.3.x/guides/ubuntu/jammy-uefi.html#create-the-zpool
https://docs.zfsbootmenu.org/en/v2.3.x/guides/ubuntu/jammy-uefi.html#export-then-re-import-with-a-temporary-mountpoint-of-mnt
https://docs.zfsbootmenu.org/en/v2.3.x/guides/ubuntu/jammy-uefi.html#copy-files-into-the-new-install
https://docs.zfsbootmenu.org/en/v2.3.x/guides/ubuntu/jammy-uefi.html#configure-initramfs-tools
https://docs.zfsbootmenu.org/en/v2.3.x/guides/ubuntu/jammy-uefi.html#install-and-configure-zfsbootmenu

I had not planned on any further work on this script as the client's work is currently completed. I'd happily except anyone's contributions to this script if other people find it helpful.
